src/Entity/ItTicket.php
<?php

namespace App\Entity;

use App\Repository\ItTicketRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ItTicketRepository::class)]
class ItTicket extends Ticket
{
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pcName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $errorCode = null;

    #[ORM\Column(length: 255)]
    private ?string $Localisation = null;

    #[ORM\ManyToOne(inversedBy: 'itTickets')]
    private ?ErrorType $ErrorType = null;

    public function getId(): ?int
    {
        return parent::getId();
    }

    public function getPcName(): ?string
    {
        return $this->pcName;
    }

    public function setPcName(string $pcName): static
    {
        $this->pcName = $pcName;

        return $this;
    }

    public function getErrorCode(): ?string
    {
        return $this->errorCode;
    }

    public function setErrorCode(?string $errorCode): static
    {
        $this->errorCode = $errorCode;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->Localisation;
    }

    public function setLocalisation(string $Localisation): static
    {
        $this->Localisation = $Localisation;

        return $this;
    }

    public function getErrorType(): ?ErrorType
    {
        return $this->ErrorType;
    }

    public function setErrorType(?ErrorType $ErrorType): static
    {
        $this->ErrorType = $ErrorType;

        return $this;
    }
}

src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: TicketRepository::class)]
#[ORM\InheritanceType('JOINED')]
#[ORM\DiscriminatorColumn(name: 'type', type: Types::STRING)]
#[ORM\DiscriminatorMap(['ticket' => Ticket::class, 'building' => BuildingTicket::class, 'it' => ItTicket::class, 'vehicle' => VehicleTicket::class])]
class Ticket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Gedmo\Timestampable(on: 'create')]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    private ?bool $solved = null;

    #[ORM\ManyToOne(inversedBy: 'tickets')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $createBy = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function isSolved(): ?bool
    {
        return $this->solved;
    }

    public function setSolved(bool $solved): static
    {
        $this->solved = $solved;

        return $this;
    }

    public function getCreateBy(): ?User
    {
        return $this->createBy;
    }

    public function setCreateBy(?User $createBy): static
    {
        $this->createBy = $createBy;

        return $this;
    }

    public function getClassName()
    {
        return (new \ReflectionClass($this))->getShortName();
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Doctrine\ORM\Mapping\InheritanceType;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[Gedmo\Uploadable(path: 'var/uploads/userProfilPicture', filenameGenerator: 'SHA1', allowOverwrite: true, appendNumber: true)]
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[InheritanceType('SINGLE_TABLE')]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[DiscriminatorMap(['admin' => Admin::class, 'user' => User::class])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $service = null;

    #[ORM\OneToMany(mappedBy: 'createBy', targetEntity: Ticket::class)]
    private Collection $tickets;

    #[ORM\Column(length: 255)]
    private ?string $post = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Gedmo\UploadableFilePath]
    private ?string $ProfilPicture = null;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getService(): ?string
    {
        return $this->service;
    }

    public function setService(string $service): static
    {
        $this->service = $service;

        return $this;
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): static
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets->add($ticket);
            $ticket->setCreateBy($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): static
    {
        if ($this->tickets->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getCreateBy() === $this) {
                $ticket->setCreateBy(null);
            }
        }

        return $this;
    }

    public function getPost(): ?string
    {
        return $this->post;
    }

    public function setPost(string $post): static
    {
        $this->post = $post;

        return $this;
    }

    public function getProfilPicture(): ?string
    {
        return $this->ProfilPicture;
    }

    public function setProfilPicture(?string $ProfilPicture): static
    {
        $this->ProfilPicture = $ProfilPicture;

        return $this;
    }
}

src/Entity/VehicleTicket.php
<?php

namespace App\Entity;

use App\Repository\VehicleTicketRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VehicleTicketRepository::class)]
class VehicleTicket extends Ticket
{
    #[ORM\Column(length: 10)]
    private ?string $immatriculation = null;

    #[ORM\Column(length: 255)]
    private ?string $Brand = null;

    public function getId(): ?int
    {
        return parent::getId();
    }

    public function getImmatriculation(): ?string
    {
        return $this->immatriculation;
    }

    public function setImmatriculation(string $immatriculation): static
    {
        $this->immatriculation = $immatriculation;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->Brand;
    }

    public function setBrand(string $Brand): static
    {
        $this->Brand = $Brand;

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Repository\TicketRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class UserController extends AbstractController
{
    private $tokenStorage;

    public function __construct(TokenStorageInterface $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }

    #[Route('/profil', name: 'app_user')]
    public function redirection(): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        if ($this->isGranted('ROLE_ADMIN')) {
            return $this->redirectToRoute('app_admin');
        } else {
            return $this->redirectToRoute('app_user_profil');
        }
    }

    #[Route('/monprofil', name: 'app_user_profil')]
    public function index(TicketRepository $ticketRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $user = $this->tokenStorage->getToken()->getUser();
        $tickets = $ticketRepository->findBy(['createBy' => $this->getUser()], ['date' => 'DESC', 'solved' => 'ASC']);

        return $this->render('user/index.html.twig', [
            'tickets' => $tickets,
            'user' => $user,
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil!
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('styles/user/profil.css') }}">
{% endblock %}

{% block javascripts %}
	{{ importmap() }}
	 <script type="module" src="{{ asset('js/ticket/show.js') }}"></script>
{% endblock %}

{% block body %}
	<div class="content">

		<div class="user">
			<div class="profil">
				<div class="profile-picture">
					<img src="{{ user.profilPicture }}" alt="User's Profile Picture">
				</div>

				<!-- User name and post -->
				<div class="user-info">
					<span class="user-name">
						<strong>Profil :
						</strong>
						{{ user.name |capitalize}}
						{{user.lastname |capitalize}}</span>
					<span class="user-post">
						<strong>Poste :</strong>
						{{ user.post|capitalize }}
					</span>
				</div>
			</div>
		</div>

		<div class="tickets">
			{% for ticket in tickets %}
				{% set date = ticket.date|date("d/M/Y") %}

				<div class="ticket">
					<div class="ticket-header">
						<h2>{{ticket.title | capitalize}}</h2>
						<span>Date de création:
							{{date}}</span>
						<span>Status:
							{{ticket.solved ? 'Resolu' : 'Non resolu'}}</span>
						<span>Type :
							{% if ticket.className == "ItTicket" %}
								Informatique
							{% elseif ticket.className == "BuildingTicket" %}
								Bâtiment
							{% elseif ticket.className == "VehicleTicket" %}
								Véhicule
							{% endif %}
						</span>
						<div class="action-button">
							<button class="view-btn">Afficher</button>
							<button class="delete-btn">
								<a href="/ticket/delete/{{ticket.getId}}">Supprimer</a>
							</button>
						</div>
					</div>
					<div class="ticket-content">
						{% if ticket.className == "ItTicket" %}
							<div class="content-item">
								<strong>Nom du pc :
								</strong>
								{{ticket.pcName}}
							</div>
							<div class="content-item">
								<strong>Code Erreur :
								</strong>
								{{ticket.errorCode}}</div>
							<div class="content-item">
								<strong>Type :</strong>
								{{ticket.errorType.lib}}</div>
							<div class="content-item">
								<strong>Lieu :</strong>
								{{ticket.localisation}}</div>

						{% elseif ticket.className == "BuildingTicket" %}
							<div class="content-item">
								<strong>Lieu :
								</strong>
								{{ticket.localisation}}</div>
							<div class="content-item">
								<strong>Lieu Precis :
								</strong>
								{{ticket.site}}
							</div>
						{% elseif ticket.className == "VehicleTicket" %}
							<div class="content-item">
								<strong>Immatriculation :
								</strong>
								{{ticket.immatriculation}}</div>
							<div class="content-item">
								<strong>Marque :
								</strong>
								{{ticket.brand}}</div>
						{% endif %}
						<div class="content-description">
							<strong>Description :</strong>
							{{ticket.description}}</div>
					</div>
				</div>

			{% endfor %}
		</div>
	</div>
{% endblock %}